# permissions for end users to view tamers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tamer-viewer-role
rules:
- apiGroups:
  - bigdata.kubernetesbigdataeg.org
  resources:
  - tamers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - bigdata.kubernetesbigdataeg.org
  resources:
  - tamers/status
  verbs:
  - get
